---
chdir : /mnt/deploy/current
pid: /mnt/deploy/shared/pids/thin.pid
socket: /mnt/deploy/shared/sockets/thin.sock
servers: 4
onebyone: true
environment: production
daemonize: true
tag: www
wait: 120
