inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - Rakefile
    - Gemfile
    - Capfile
    - config.ru
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'editor/**/*'
    - 'backend-mock/**/*'


Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

#Metrics/LineLength:
#  Max: 130
#
#Metrics/AbcSize:
#  Max: 16