Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - Rakefile
    - Gemfile
    - Capfile
    - config.ru
    - '**/*.rake'
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'editor/**/*'
    - 'backend-mock/**/*'

#### BEGIN STYLES

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

# Configuration parameters: AutoCorrect, EnforcedStyle, SupportedStyles.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/AlignHash:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Configuration parameters: SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_brackets
Layout/IndentArray:
  EnforcedStyle: consistent

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Layout/IndentHash:
  EnforcedStyle: consistent

# Configuration parameters: EnforcedOctalStyle, SupportedOctalStyles.
# SupportedOctalStyles: zero_with_o, zero_only
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/WordArray:
  # The `MinSize` option causes the `WordArray` rule to be ignored for arrays
  # smaller than a certain size.  The rule is only applied to arrays
  # whose element count is greater than or equal to `MinSize`.
  MinSize: 3

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Naming/FileName:
  Exclude:
    - Guardfile

Style/MethodMissing:
  Exclude:
    - app/system/settings.rb

Lint/AmbiguousBlockAssociation:
  Enabled: false

#### END STYLES

#### BEGIN RAILS

# TODO: enable after updating rails/rspec
Rails/HttpPositionalArguments:
  Enabled: false

# Configuration parameters: Blacklist.
# Blacklist: decrement!, decrement_counter, increment!, increment_counter, toggle!, touch, update_all, update_attribute, update_column, update_columns, update_counters
Rails/SkipsModelValidations:
  Enabled: false

# SupportedStyles: referer, referrer
Rails/RequestReferer:
  EnforcedStyle: referrer

# TODO enable when using Rails 5
Rails/ApplicationRecord:
  Enabled: false

#### END RAILS


#### BEGIN METRICS

Metrics/AbcSize:
  Max: 49 # ideally 16

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 50 # ideally 25
  Exclude:
    - 'spec/**/*'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'lib/tasks/backend.rake'

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 185 # ideally 100
  Exclude:
    - 'app/models/site.rb'
    - 'app/models/site_element.rb'
    - 'app/models/static_script_model.rb'
    - 'app/models/user.rb'

Metrics/CyclomaticComplexity:
  Max: 17 # ideally 6

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 546 # ideally 120
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Max: 32 # ideally 10
  CountComments: false

Metrics/ModuleLength:
  Max: 176 # ideally 10
  CountComments: false

Metrics/PerceivedComplexity:
  Max: 14 # ideally 7

#### END METRICS
