inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - Rakefile
    - Gemfile
    - Capfile
    - config.ru
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'editor/**/*'
    - 'backend-mock/**/*'


Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

#Metrics/LineLength:
#  Max: 130
#
#Metrics/AbcSize:
#  Max: 16

# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
  Exclude:
    - spec/teaspoon_env.rb

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Security/MarshalLoad:
  Exclude:
    - 'lib/grand_central_api.rb'

# Configuration parameters: SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_brackets
Style/IndentArray:
  EnforcedStyle: consistent

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  EnforcedStyle: consistent

# Configuration parameters: EnforcedOctalStyle, SupportedOctalStyles.
# SupportedOctalStyles: zero_with_o, zero_only
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

# Configuration parameters: AutoCorrect, EnforcedStyle, SupportedStyles.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Enabled: false

# TODO: enable after updating rails/rspec
# Configuration parameters: Include.
# Include: spec/**/*, test/**/*
Rails/HttpPositionalArguments:
  Enabled: false

# SupportedStyles: referer, referrer
Rails/RequestReferer:
  EnforcedStyle: referrer

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodDefParentheses:
  Enabled: false
