version: 2
jobs:
  build:
    docker:
      - image: ruby:2.1.9
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
    working_directory: /tmp/hellobar_new
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -qq -y --no-install-recommends \
            build-essential git qt5-default libqt5webkit5-dev && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Bundler
          command: gem install bundler && bundle config git.allow_insecure true && bundle config github.https true
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: DB Migrations
          command: bundle exec rake db:migrate
      - run:
          name: Run Tests
          command: bundle exec rake test
