codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: "0.3%"
    patch:
      default:
        threshold: "3%"

ignore:
  - "lib/git_utils.rb"
  - "app/controllers/heartbeat_controller.rb"
  - "app/controllers/modals_controller.rb"
  - "app/controllers/proxy_controller.rb"
  - "app/services/upload_subscriptions_to_profitwell.rb"
