version: '2'
services:
  db:
    image: mysql
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: bundle exec thin start
    ports:
      - "80:3000"
    links:
      - db:mysql
    volumes:
      - ./:/docker/hellobar
