version: '2'
services:
  db:
    image: mysql
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: hb
      MYSQL_DATABASE: new_hellobar_development
      MYSQL_PASSWORD: hbpass
    networks:
      - back
  web:
    build: .
    command: bin/entrypoint
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - '.:/app'
    environment:
      DATABASE_URL: mysql2://hb:hbpass@db:3306/new_hellobar_development?encoding=utf8&pool=5&username=root&password=root
    networks:
      - back
      - front

networks:
  back:
  front:
