version: '2'
services:
  db:
    image: mysql
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  agent:
    image: whilp/ssh-agent
  selenium-firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - "4444"
      - "5900"
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444"
      - "5900"
  web:
    build:
      context: .
      args:
        APP: hellobar
    command: bundle exec thin start
    ports:
      - "80:3000"
    links:
      - db:mysql
      - selenium-firefox
      - selenium-chrome
    volumes:
      - ./:/docker/hellobar
    volumes_from:
      - agent
    environment:
      DOCKER: 1
      SSH_AUTH_SOCK: /root/.ssh/socket
