source "https://rubygems.org"

gem "active_link_to",            "~> 1.0.2"
gem "active_model_serializers",  "~> 0.8.1"
gem "addressable",               "~> 2.3.6", :require => "addressable/uri"
gem "avatar",                    "~> 0.2.0"
gem "aweber",                    "~> 1.6.1"
gem "aws-sdk",                   "1.33.0"
gem "bootstrap-sass",            "~> 3.1.1"
gem "bourbon",                   "~> 3.2.0"
gem "capistrano",                "~> 3.1"
gem "capistrano-bundler",        "~> 1.1.2"
gem "capistrano-rails",          "~> 1.1"
gem "coffee-rails",              "~> 4.0.0"
gem "constantcontact",           "~> 1.1.2"
gem "createsend",                "~> 3.4.0"
gem "cssmin",                    "~> 1.0.3"
gem "devise",                    "~> 3.2.4"
gem "ember-rails",               "~> 0.15.0"
gem "ember-source",              "~> 1.5.1.1"
gem "fog",                       "~> 1.22.1"
gem "gibbon",                    "~> 1.0.4"
gem "guaranteed_queue",          "~> 0.0.1", :github => "colinyoung/guaranteed_queue"
gem "hashie",                    "~> 2.1.1"
gem "jbuilder",                  "~> 2.0"
gem "jquery-rails",              "~> 3.1.0"
gem "kaminari",                  "~> 0.15.1"
gem "mustache",                  "~> 0.99.5"
gem "mysql2",                    "0.3.16"
gem "omniauth",                  "~> 1.0"
gem "omniauth-aweber",           "~> 1.0"
gem "omniauth-constantcontact2", "~> 1.0"
gem "omniauth-createsend",       "~> 1.0"
gem "omniauth-mailchimp",        "~> 1.0",   :github => "floomoon/omniauth-mailchimp"
gem "pony",                      "~> 1.8"
gem "psych",                     "~> 2.0.5"
gem "rails",                     "4.1.1"
gem "rb-readline",               "~> 0.5.1"
gem "recaptcha",                 "~> 0.3.6", :require => "recaptcha/rails"
gem "render_anywhere",           "~> 0.0.9"
gem "sass-rails",                "~> 4.0.3"
gem "sentry-raven",              "~> 0.9"
gem "simple_form",               "3.1.0.rc1"
gem "slim-rails",                "~> 2.1.4"
gem "thin",                      "~> 1.6.2"
gem "twilio-ruby",               "~> 3.11.5"
gem "uglifier",                  "2.0.1"
gem "unf",                       "~> 0.1.4"
gem "whenever",                  "~> 0.9.2"
gem "zip",                       "~> 2.0.2"

group :development do
  gem "better_errors", "~> 1.1"
  gem "binding_of_caller"
end

group :development, :test do
  gem "debugger"
  gem "metric_fu"
  gem "minitest"
  gem "pry"
  gem "rspec-rails", "~> 2.14"
  gem "teaspoon", "~> 0.8.0"
  gem "simplecov", "~> 0.7.1"
end

group :test do
  gem "timecop"
  gem "vcr"
  gem "webmock"
  gem "zonebie", "~> 0.5.1"
  gem "database_cleaner", '~> 1.3'
end
