source "https://rubygems.org"

gem "active_model_serializers"
gem "addressable", "~> 2.3.6", :require => "addressable/uri"
gem "avatar"
gem "aws-sdk", "1.33.0"
gem "bootstrap-sass", "~> 3.1.1"
gem "bourbon", "~> 3.2.0"
gem "capistrano", "~> 3.1"
gem "capistrano-bundler", "~> 1.1.2"
gem "capistrano-rails", "~> 1.1"
gem "coffee-rails", "~> 4.0.0"
gem "cssmin", "~> 1.0.3"
gem "devise"
gem "ember-source", "~> 1.5.1.1"
gem "ember-rails"
gem "fog"
gem "gridle-rails"
gem "guaranteed_queue", :github => "colinyoung/guaranteed_queue"
gem "jbuilder", "~> 2.0"
gem "jquery-rails"
gem "kaminari"
gem "mustache", "~> 0.99.5"
gem "mysql2"
gem "pony"
gem "psych"
gem "rails", "4.1.1"
gem "rb-readline"
gem "recaptcha", :require => "recaptcha/rails"
gem "render_anywhere"
gem "sass-rails", "~> 4.0.3"
gem "simple_form", "3.1.0.rc1"
gem "slim-rails"
gem "thin"
gem "twilio-ruby"
gem "uglifier", "2.0.1"
gem "unf"
gem "whenever"
gem "zip"

group :development, :test do
  gem "debugger"
  gem "minitest"
  gem "pry"
  gem "rspec-rails", "~> 2.14"
  gem "autotest-rails"
  gem "metric_fu"
  gem 'simplecov'
end

group :test do
  gem "timecop"
  gem "vcr"
  gem "webmock"
end
