source "http://rubygems.org"

gem "abanalyzer"
gem "active_link_to",            "~> 1.0.2"
gem "active_model_serializers",  "~> 0.9.3"
gem "activemerchant",            "~> 1.44.1"
gem "addressable",               "~> 2.3.6", :require => "addressable/uri"
gem "avatar",                    "~> 0.2.0"
gem "aweber",                    "~> 1.6.1"
gem "aws-sdk",                   "~> 1.66.0"
gem "bootstrap-sass",            "~> 3.1.1"
gem "bourbon",                   "~> 3.2.0"
gem "capistrano",                "~> 3.1"
gem "capistrano-bundler",        "~> 1.1.2"
gem "capistrano-rails",          "~> 1.1"
gem "coffee-rails",              "~> 4.0.0"
gem "constantcontact",           "~> 1.1.2"
gem "country_select",            "~> 2.1.0", github: 'stefanpenner/country_select'
gem "createsend",                "~> 3.4.0"
gem "cssmin",                    "~> 1.0.3"
gem "dalli",                     "~> 2.7.2"
gem "devise",                    "~> 3.2.4"
gem "drip-ruby",                 "~> 0.0.3", require: 'drip'
gem "ember-rails",               "~> 0.16.4"
gem "ember-source",              "~> 1.7.1"
gem "figaro",                    "~> 1.0.0"
gem "fog",                       "~> 1.22.1"
gem "gibbon",                    "~> 1.0.4"
gem "hashie",                    "~> 2.1.1"
gem "jbuilder",                  "~> 2.0"
gem "jquery-rails",              "~> 3.1.0"
gem "kaminari",                  "~> 0.15.1"
gem "less_interactions",         "0.0.15"
gem "logglier"
gem "mustache",                  "~> 0.99.5"
gem "mysql2",                    "0.3.16"
gem "omniauth",                  "~> 1.0"
gem "omniauth-aweber",           "~> 1.0"
gem "omniauth-constantcontact2", "~> 1.0"
gem "omniauth-createsend",       "~> 1.0"
gem "omniauth-google-oauth2",    "~> 0.2.6"
gem "omniauth-mailchimp",        "~> 1.0",   :github => "floomoon/omniauth-mailchimp"
gem "paranoia",                  "~> 2.0"
gem "php-serialize",                         :require => "php_serialize"
gem "phpass-ruby",                           :require => "phpass"
gem "pony",                      "~> 1.8"
gem "psych",                     "~> 2.0.5"
gem "public_suffix",             "~> 1.5.1"
gem 'rack-ssl-enforcer',         "~> 0.2.8"
gem "rails",                     "4.1.5"
gem "rake_running",              "~> 0.0.1", :github => "colinyoung/rake_running"
gem "rb-readline",               "~> 0.5.1"
gem "recaptcha",                 "~> 0.3.6", :require => "recaptcha/rails"
gem "render_anywhere",           "~> 0.0.9"
gem "roadie-rails"
gem "ruby-hmac"
gem "sass-rails",                "~> 4.0.3"
gem "sentry-raven",              "~> 0.9"
gem "simple_form",               "3.1.0.rc1"
gem "slim-rails",                "~> 2.1.4"
gem "thin",                      "~> 1.6.2"
gem "twilio-ruby",               "~> 3.11.5"
gem "uglifier",                  "2.0.1"
gem "unf",                       "~> 0.1.4"
gem "whenever",                  "~> 0.9.2"
gem 'rubyzip', '>= 1.0.0' # will load new rubyzip version
gem 'zip-zip' # will load compatibility for old rubyzip API.
gem "paperclip",                 "~> 4.3"
gem "elif",                      "~> 0.1"
gem "thread",                    "~> 0.2.2"

group :development do
  gem "better_errors", "~> 1.1"
  gem "binding_of_caller"
  gem "sinatra"
end

group :development, :test do
  gem "byebug"
  gem "capybara"
  gem "capybara-webkit"
  gem 'selenium-webdriver'
  gem "factory_girl_rails"
  gem "faker"
  gem "metric_fu"
  gem "minitest"
  gem "pry"
  gem "pry-nav"
  gem "rspec-rails", "~> 2.14"
  gem "simplecov", "~> 0.7.1"
  gem "teaspoon-jasmine"
end

group :test do
  gem 'rspec_junit_formatter', '~> 0.2.2'
  gem "database_cleaner", '~> 1.3'
  gem "fivemat"
  gem "timecop"
  gem "vcr"
  gem "webmock"
  gem "zonebie", "~> 0.5.1"
end
