import Ember from 'ember';

export default Ember.Service.extend({
  fontFamily() {
    return {
      "Arial,Helvetica,sans-serif": 'Arial',
      "'Bevan', cursive": 'Bevan',
      "'Bree Serif', serif": 'Bree Serif',
      "'Chela One', cursive": 'Chela One',
      "'Cinzel', serif": 'Cinzel',
      "'Fugaz One', cursive": 'Fugaz One',
      "Georgia,serif": 'Georgia',
      "Impact, Charcoal, sans-serif": 'Impact',
      "'Josefin Sans',sans-serif": 'Josefin Sans',
      "'Julius Sans One', sans-serif": 'Julius Sans One',
      "'Kanit', sans-serif": 'Kanit',
      "Lato,sans-serif": 'Lato',
      "'Libre Baskerville',sans-serif": 'Libre Baskerville',
      "'Lobster', cursive": 'Lobster',
      "'Merienda', cursive": 'Merienda',
      "'Monoton', cursive": 'Monoton',
      "Montserrat,sans-serif": 'Montserrat',
      "'Oleo Script', cursive": 'Oleo Script',
      "'Open Sans',sans-serif": 'Open Sans',
      "Oswald,sans-serif": 'Oswald',
      "'Pacifico', cursive": 'Pacifico',
      "'Paytone One', sans-serif": 'Paytone One',
      "'Permanent Marker', cursive": 'Permanent Marker',
      "'Poiret One', cursive": 'Poiret One',
      "'PT Sans',sans-serif": 'PT Sans',
      "'PT Serif',sans-serif": 'PT Serif',
      "Raleway, sans-serif": 'Raleway',
      "Roboto,sans-serif": 'Roboto',
      "'Rock Salt', cursive": 'Rock Salt',
      "'Sintony',sans-serif": 'Sintony',
      "'Source Sans Pro',sans-serif": 'Source Sans Pro',
      "'Special Elite', cursive": 'Special Elite',
      "Tahoma, Geneva, sans-serif": 'Tahoma',
      "\'Times New Roman\', Times, serif": 'Times New Roman',
      "'Ubuntu Condensed', sans-serif": 'Ubuntu Condensed',
      "Verdana, Geneva, sans-serif": 'Verdana',
      "'Open Sans Condensed', sans-serif":'Open Sans Condensed',
      "'Playfair Display', serif":'Playfair Display',
      "'Spirax', cursive": 'Spirax',
      "'Anton', sans-serif": 'Anton',
      "'Abril Fatface', cursive":'Abril Fatface',
      "'Coiny', cursive":'Coiny',
      "'Cinzel', serif":'Cinzel',
      "'Rajdhani', sans-serif":'Rajdhani',
      "'Kavoon', cursive":'Kavoon',
      "'Notable', sans-serif":'Notable',
      "'Philosopher', sans-serif":'Philosopher',
      "'Ultra', serif":'Ultra',
      "'Martel', serif":'Martel',
      "'Prata', serif":'Prata',
      "'Julius Sans One', sans-serif":'Julius Sans One',
      "'Antic Slab', serif":'Antic Slab',
      "'Berkshire Swash', cursive":'Berkshire Swash',
      "'Aclonica', sans-serif":'Aclonica',
      "'Bungee Inline', cursive":'Bungee Inline'
    };
  },

  googleFonts() {
    return [
      'Bevan',
      'Bree+Serif',
      'Chela+One',
      'Cinzel',
      'Fugaz+One',
      'Josefin+Sans',
      'Julius+Sans+One',
      'Lato',
      'Libre+Baskerville',
      'Kanit',
      'Lobster',
      'Merienda',
      'Monoton',
      'Montserrat',
      'Oleo+Script',
      'Open Sans',
      'Oswald',
      'Pacifico',
      'Paytone+One',
      'Permanent+Marker',
      'Poiret+One',
      'PT Sans',
      'PT Serif',
      'Raleway',
      'Roboto',
      'Rock+Salt',
      'Sintony',
      'Special+Elite',
      'Source+Sans+Pro',
      'Ubuntu+Condensed',
      'Open+Sans+Condensed:300',
      'Playfair+Display',
      'Spirax',
      'Anton',
      'Abril+Fatface',
      'Coiny',
      'Cinzel',
      'Rajdhani',
      'Kavoon',
      'Notable',
      'Philosopher',
      'Ultra',
      'Martel',
      'Prata',
      'Julius+Sans+One',
      'Antic+Slab',
      'Berkshire+Swash',
      'Aclonica',
      'Bungee+Inline'

    ];
  }
});
