source 'https://rubygems.org'

# Specify your gem's dependencies in service_providers.gemspec
gemspec

gem 'active_campaign', '~> 0.1.14'
gem 'aweber'
gem 'constantcontact'
gem 'createsend' # CampaignMonitor
gem 'drip-ruby', require: 'drip'
gem 'gibbon' # MailChimp
gem 'infusionsoft'
gem 'madmimi'
gem 'omniauth-aweber', '~> 1.0'
gem 'omniauth-constantcontact2', '~> 1.0'
gem 'omniauth-createsend', '~> 1.0'
gem 'omniauth-mailchimp', github: 'floomoon/omniauth-mailchimp', ref: '239e08d3297cf637b5b0b77b419fdc8461239378'
gem 'omniauth-verticalresponse', '~> 1.0.0'
gem 'verticalresponse'
