#!/usr/bin/env ruby

require 'yaml'
require 'aws-sdk'

STAGES = %w(edge staging production)
BASEDIR = File.expand_path(File.dirname(__FILE__)).gsub('/script', '')
SETTINGS_FILE = BASEDIR + '/config/settings.yml'

def die!(message)
  puts "Usage: send_sqs_message [stage] [command] [queue_name=nil]\n" + message
  exit!
end

if File.exists?(SETTINGS_FILE)
  settings = YAML.load_file(SETTINGS_FILE)
else
  die!("Settings file not present.")
end

# Sends a message to SQS without loading Rails environment
stage, message, queue_name = *ARGV
die!("Stage is required to be one of #{STAGES}") unless STAGES.include?(stage)
die!("Command not present!") unless message && message.length > 0

key = settings['aws_access_key_id']
secret = settings['aws_secret_access_key']
queue_name ||= settings['main_queue'] || 'test_queue'

die!("Queue name not set") unless queue_name

sqs = AWS::SQS.new(access_key_id: key, secret_access_key: secret)

queue = sqs.queues.find do |q|
  q.url.split('/').last == queue_name
end

# fail 'Queue seems incorrect for that stage' unless queue.url.include?(stage)

puts "[#{Time.now}] Sending #{message} to #{queue.url}"
receipt = queue.send_message(message)
p receipt
